forums:
  - name: "breachforums-Stealer-Logs"
    url: "https://breachforums.bf/Forum-Stealer-Logs?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > table.tborder.clear > tbody > tr:nth-child(7) > td:nth-child(2) > div > div:nth-child(1)"
    is_onion: false
    type: "forum-post"

  - name: "breachforums-database"
    url: "https://breachforums.bf/Forum-Databases?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > table.tborder.clear > tbody > tr:nth-child(14) > td:nth-child(2) > div > div:nth-child(1)"
    is_onion: false
    type: "forum-post"

  - name: "breachforums-combolist"
    url: "https://breachforums.bf/Forum-Combolists?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > table.tborder.clear > tbody > tr:nth-child(7) > td:nth-child(2) > div > div:nth-child(1)"
    is_onion: false
    type: "forum-post"

  - name: "breachforums-accounts"
    url: "https://breachforums.bf/Forum-Cracked-Accounts?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > table > tbody > tr:nth-child(7) > td:nth-child(2) > div > div:nth-child(1)"
    is_onion: false
    type: "forum-post"
