forums:
  - name: "darkforums-database"
    url: "https://darkforums.io/Forum-Databases?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#forum-display > table > tbody > tr:nth-child(6)"
    is_onion: false
    selectors:
      link: "span.subject_new a"
      title: "span.subject_new a"
      author: ".author a"
