forums:
  - name: "breachforums-Stealer-Logs"
    url: "https://breachforums.bf/Forum-Stealer-Logs?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > table.tborder.clear > tbody > tr:nth-child(7)"
    is_onion: false
    type: "forum-post"

  - name: "breachforums-database"
    url: "https://breachforums.bf/Forum-Databases?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > table.tborder.clear > tbody > tr:nth-child(14)"
    is_onion: false
    type: "forum-post"

  - name: "breachforums-combolist"
    url: "https://breachforums.bf/Forum-Combolists?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > table.tborder.clear > tbody > tr:nth-child(7)"
    is_onion: false
    type: "forum-post"

  - name: "breachforums-accounts"
    url: "https://breachforums.bf/Forum-Cracked-Accounts?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > table > tbody > tr:nth-child(7)"
    is_onion: false
    type: "forum-post"

  - name: "darkforums"
    url: "https://darkforums.io/"
    css_selector: "#general > div > div:nth-child(1)"
    is_onion: false
    type: "forum-post"

  - name: "xforums"
    url: "https://xforums.st/forums/database-log-pass-number-pass.34/"
    css_selector: "#top > div.p-body-inner > div.p-body-main.is-active > div.p-body-content.is-active > div > div > div.block-container.block-container--nodes > div.block-body > div > div > div.structItem:nth-child(1)"
    is_onion: false
    type: "forum-post"

  - name: "hydra-database"
    url: "https://hydraforums.io/Forums-database-logs-combolist?sortby=started&order=desc&datecut=9999"
    css_selector: "span.subject_new a"
    is_onion: false
    type: "forum-post"

  - name: "crackingx-database"
    url: "https://crackingx.com/forums/5/?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#top > div.p-body > div > div.uix_contentWrapper > div > div > div > div > div.block-container.uix_discussionList > div.block-body > div > div.structItemContainer-group.js-threadList > div.structItem.structItem--thread.is-prefix1.js-inlineModContainer:nth-child(1) > div.structItem-cell.structItem-cell--main"
    is_onion: false
    type: "forum-post"

  - name: "crackingx-accounts"
    url: "https://crackingx.com/forums/17/?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#top > div.p-body > div > div.uix_contentWrapper > div > div > div > div > div.block-container.uix_discussionList > div.block-body > div > div > div.structItem.structItem--thread.js-inlineModContainer:nth-child(1) > div.structItem-cell.structItem-cell--main"
    is_onion: false
    type: "forum-post"

  - name: "niflhemim-account"
    url: "https://niflheim.world/forums/accounts.8/"
    css_selector: "#top > div.p-body > div > div.p-body-main.xtr-sidebar-default > div > div > div.block > div.block-container > div.block-body > div > div > div > div.structItem.structItem--thread.js-inlineModContainer:nth-child(1)"
    is_onion: false
    type: "forum-post"

  - name: "niflhemim-combolist"
    url: "https://niflheim.world/forums/combolist.2/"
    css_selector: "#top > div.p-body > div > div.p-body-main.xtr-sidebar-default > div > div > div.block > div.block-container > div.block-body > div > div.structItemContainer-group.js-threadList > div > div.structItem.structItem--thread.is-prefix5.js-inlineModContainer:nth-child(1)"
    is_onion: false
    type: "forum-post"

  - name: "patched-accounts"
    url: "https://patched.to/Forum-accounts?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > div > table.tborder.clear.patched > tbody > tr:nth-child(4) > td:nth-child(2) > div:nth-child(1) > span"
    is_onion: false
    type: "forum-post"

  - name: "patched-combolist"
    url: "https://patched.to/Forum-combolist?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "#content > div > table > tbody > tr:nth-child(3) > td:nth-child(2) > div:nth-child(1) > span"
    is_onion: false
    type: "forum-post"

  - name: "xreactor"
    url: "https://xreactor.org/#tab-1"
    css_selector: "#tab-1 > div > div > ul > li:nth-child(1)"
    is_onion: false
    type: "forum-post"

  - name: "darkforums-Databases"
    url: "https://darkforums.io/Forum-Databases?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "tr.inline_row span.subject_new a"
    is_onion: false
    type: "forum-post"

  - name: "darkforums-Stealer-Logs"
    url: "https://darkforums.io/Forum-Stealer-Logs?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "tr.inline_row:first-child span.subject_new a"
    is_onion: false
    type: "forum-post"

  - name: "darkforums-Combolists"
    url: "https://darkforums.io/Forum-Combolists?sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "tr.inline_row span.subject_new a"
    is_onion: false
    type: "forum-post"

  - name: "leakzone-databases"
    url: "https://leakzone.net/forumdisplay.php?fid=20&sortby=started&order=desc&datecut=9999&prefix=0"
    css_selector: "tr.inline_row:first-child span.subject_new a"
    is_onion: false
    type: "forum-post"
